spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/data_jpa
    username: tommy
    password: tommy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    show-sql: true